In [9]:
import pandas as pd

In [10]:
import numpy as np

In [11]:
# load dates for to examine induced demand on

tue_before =  pd.read_csv("../nanjing-data/20150303.csv", header=None)
wed_before = pd.read_csv("../nanjing-data/20150304.csv", header=None)
thu_before = pd.read_csv("../nanjing-data/20150305.csv", header=None)
tue_after =  pd.read_csv("../nanjing-data/20150428.csv", header=None)
wed_after = pd.read_csv("../nanjing-data/20150429.csv", header=None)
thu_after = pd.read_csv("../nanjing-data/20150430.csv", header=None)
tempcol = pd.read_csv("../nanjing-data/header.csv")
tue_before.columns=tempcol.columns
wed_before.columns=tempcol.columns
thu_before.columns=tempcol.columns
tue_after.columns=tempcol.columns
wed_after.columns=tempcol.columns
thu_after.columns=tempcol.columns

In [12]:
# concatenate after dates together
frames = [tue_after, wed_after, thu_after]
all_after = pd.concat(frames)
all_after

,Card_Id,Card_Id_Long,Card_Type,Fare,Time,Entry_Or_Exit,Line_Id,StationId,Device_Id
0,996162764252,08043652BA95208000,53,0.0,2015-04-28 06:01:06,1,4,1,12.0
1,992294737220,0804094201461D8000,52,0.0,2015-04-28 06:06:35,1,4,1,12.0
2,990164163623,0804364FEA04208000,52,0.0,2015-04-28 07:37:56,1,4,1,12.0
3,990163914237,08041D222ABE208000,52,0.0,2015-04-28 07:38:08,1,4,1,12.0
4,996170494223,0804345B6A442B8000,53,0.0,2015-04-28 07:38:11,1,4,1,12.0
5,996363453168,080433169A1D1D8000,53,0.0,2015-04-28 07:38:30,1,4,1,12.0
6,997164834854,0804515DC2D2238000,85,0.0,2015-04-28 07:38:42,1,4,1,12.0
7,997164417372,0804205BFAB0238000,83,0.0,2015-04-28 07:39:17,1,4,1,12.0
8,996161627845,08046A36B1AC228000,53,0.0,2015-04-28 07:39:51,1,4,1,12.0
9,990772898936,08044B5C5A84368000,88,0.0,2015-04-28 07:40:20,1,4,1,12.0
10,990263769336,08043C2D3A2A238000,52,0.0,2015-04-28 07:40:39,1,4,1,12.0
11,990163990426,0804452FB2B9238000,52,0.0,2015-04-28 07:40:44,1,4,1,12.0
12,996572206548,08044408822A358000,53,0.0,2015-04-28 07:41:16,1,4,1,12.0
13,990363473980,08041216CAB2208000,52,0.0,2015-04-28 07:41:39,1,4,1,12.0
14,990774300974,0804423F1AB0348000,88,0.0,2015-04-28 07:41:49,1,4,1,12.0
15,990772078793,080443565A4B2B8000,52,0.0,2015-04-28 07:42:13,1,4,1,12.0
16,970471559909,080E211BBA153C3500,52,0.0,2015-04-28 07:42:58,1,4,1,12.0
17,996060341323,08043F59116F1C8000,53,0.0,2015-04-28 07:43:02,1,4,1,12.0
18,996195783914,08042155F9841D8000,53,0.0,2015-04-28 07:43:26,1,4,1,12.0
19,976471285726,080E208A1F0A1F1000,53,0.0,2015-04-28 07:44:02,1,4,1,12.0
20,990361949023,0804222B91BE228000,52,0.0,2015-04-28 07:44:08,1,4,1,12.0
21,996160604213,08042F5AF90C1C8000,53,0.0,2015-04-28 07:44:20,1,4,1,12.0
22,973674678948,080E3A17590E435800,85,0.0,2015-04-28 06:07:35,1,4,1,12.0
23,997163548852,08042E3442731F8000,85,0.0,2015-04-28 06:09:53,1,4,1,12.0
24,996160098851,0804382889701B8000,53,0.0,2015-04-28 06:15:33,1,4,1,12.0
25,996096218219,0804523911921B8000,53,0.0,2015-04-28 07:00:53,1,4,1,12.0
26,970071639112,08CF69960434200800,52,0.0,2015-04-28 07:03:31,1,4,1,12.0
27,997166723151,08042817D2EC238000,55,0.0,2015-04-28 07:05:56,1,4,1,12.0
28,991260029430,0804351401B31B8000,52,0.0,2015-04-28 07:44:38,1,4,1,12.0
29,990572686457,08042811CA85368000,52,0.0,2015-04-28 07:46:03,1,4,1,12.0
...,...,...,...,...,...,...,...,...,...
2309470,996262049497,08042E0DC2321E8000,53,190.0,2015-04-30 18:44:03,2,1,9,1.0
2309471,996161291983,08041D4A31AE238000,53,190.0,2015-04-30 18:44:06,2,1,9,1.0
2309472,996096236072,0804093911921B8000,53,190.0,2015-04-30 18:44:09,2,1,9,1.0
2309473,996096337749,0804504A41B31B8000,53,190.0,2015-04-30 18:44:12,2,1,9,1.0
2309474,990261602800,08041B38F1F11B8000,52,150.0,2015-04-30 18:44:15,2,1,9,1.0
2309475,996295097912,0804322DB9AA1C8000,53,150.0,2015-04-30 18:44:18,2,1,9,1.0
2309476,976674236590,088D3212940717D200,53,190.0,2015-04-30 18:44:35,2,1,9,1.0
2309477,996160611765,08045B3921001F8000,53,190.0,2015-04-30 18:44:38,2,1,9,1.0
2309478,996570870009,08042C5AAA412C8000,53,150.0,2015-04-30 18:44:40,2,1,9,1.0
2309479,990770738265,08046217823F2F8000,52,190.0,2015-04-30 18:44:51,2,1,9,1.0
2309480,996096185108,0804385F91901B8000,53,150.0,2015-04-30 18:44:53,2,1,9,1.0
2309481,995258319906,0804373552FF228000,52,190.0,2015-04-30 18:45:01,2,1,9,1.0
2309482,996096170783,08043E3929901B8000,53,190.0,2015-04-30 18:45:03,2,1,9,1.0
2309483,996572106151,08043538128C338000,53,285.0,2015-04-30 18:45:19,2,1,9,1.0
2309484,970672792588,080D3710580AA9BA00,52,190.0,2015-04-30 18:45:22,2,1,9,1.0
2309485,990163538317,08045341921F1D8000,52,190.0,2015-04-30 18:46:05,2,1,9,1.0
2309486,990772915708,0804420CA283358000,88,190.0,2015-04-30 19:29:31,2,1,14,11.0
2309487,996163834414,08043225AA2F238000,53,190.0,2015-04-30 19:30:33,2,1,14,11.0
2309488,970472621063,080E2285AB150E2500,52,285.0,2015-04-30 19:30:36,2,1,14,11.0
2309489,976673063140,080D3710660A088E00,53,150.0,2015-04-30 19:30:43,2,1,14,11.0
2309490,970672776748,080D2914671783B100,52,190.0,2015-04-30 19:30:45,2,1,14,11.0
2309491,990572716006,080436126A84368000,52,380.0,2015-04-30 19:30:48,2,1,14,11.0
2309492,990571157745,08041B4EDA39318000,52,340.0,2015-04-30 19:30:54,2,1,14,11.0
2309493,996060349674,0804511029841D8000,53,190.0,2015-04-30 19:30:59,2,1,14,11.0
2309494,990172172398,08045A404AA3328000,52,150.0,2015-04-30 19:31:02,2,1,14,11.0
2309495,990773066764,080D3710471987D400,52,190.0,2015-04-30 19:31:08,2,1,14,11.0
2309496,970674210990,080D371066059FD400,52,475.0,2015-04-30 19:31:20,2,1,14,11.0
2309497,996172342465,080448176A8C338000,53,475.0,2015-04-30 19:31:36,2,1,14,11.0
2309498,997168296933,08045E406A612B8000,80,190.0,2015-04-30 19:31:50,2,1,14,11.0
2309499,990172194410,08046A379AA1328000,52,150.0,2015-04-30 19:31:51,2,1,14,11.0

In [14]:
# Find ids that were not in BEFORE (tues,wed,thu) but are in AFTER(all)
id_in_both = list(set(tue_before['Card_Id']).intersection(all_after['Card_Id']))
all_unique=all_after[~all_after['Card_Id'].isin(id_in_both)]
id_in_both = list(set(wed_before['Card_Id']).intersection(all_after['Card_Id']))
all_unique=all_unique[~all_unique['Card_Id'].isin(id_in_both)]
id_in_both = list(set(thu_before['Card_Id']).intersection(all_after['Card_Id']))
all_unique=all_unique[~all_unique['Card_Id'].isin(id_in_both)]
all_unique

,Card_Id,Card_Id_Long,Card_Type,Fare,Time,Entry_Or_Exit,Line_Id,StationId,Device_Id
8,996161627845,08046A36B1AC228000,53,0.0,2015-04-28 07:39:51,1,4,1,12.0
16,970471559909,080E211BBA153C3500,52,0.0,2015-04-28 07:42:58,1,4,1,12.0
17,996060341323,08043F59116F1C8000,53,0.0,2015-04-28 07:43:02,1,4,1,12.0
18,996195783914,08042155F9841D8000,53,0.0,2015-04-28 07:43:26,1,4,1,12.0
20,990361949023,0804222B91BE228000,52,0.0,2015-04-28 07:44:08,1,4,1,12.0
22,973674678948,080E3A17590E435800,85,0.0,2015-04-28 06:07:35,1,4,1,12.0
28,991260029430,0804351401B31B8000,52,0.0,2015-04-28 07:44:38,1,4,1,12.0
29,990572686457,08042811CA85368000,52,0.0,2015-04-28 07:46:03,1,4,1,12.0
30,996500042376,0804313532E8268000,53,0.0,2015-04-28 07:47:21,1,4,1,12.0
32,996195815836,08044126D1841D8000,53,0.0,2015-04-28 06:40:41,1,4,1,12.0
43,990172169674,0804203E82A3328000,52,0.0,2015-04-28 07:48:50,1,4,1,12.0
45,996362716215,0804121CB295208000,53,0.0,2015-04-28 07:49:36,1,4,1,12.0
46,990164071738,0804553CBA15268000,52,0.0,2015-04-28 07:50:00,1,4,1,12.0
47,996161774922,08040D2551251C8000,53,0.0,2015-04-28 07:50:11,1,4,1,12.0
48,990170530041,08044D36EA432B8000,52,0.0,2015-04-28 07:50:46,1,4,1,12.0
50,996195915817,08046D3799841D8000,53,0.0,2015-04-28 07:51:50,1,4,1,12.0
55,996195932789,08044060D9731B8000,53,0.0,2015-04-28 07:53:46,1,4,1,12.0
58,973671366905,080D2914660F96D100,85,0.0,2015-04-28 07:55:40,1,4,1,12.0
60,990572674159,0804651BB279358000,52,0.0,2015-04-28 07:57:08,1,4,1,12.0
64,997169435001,08042B30CA73348000,80,0.0,2015-04-28 06:25:25,1,4,1,12.0
67,996572487041,08041F272A83358000,53,0.0,2015-04-28 07:24:46,1,4,1,12.0
69,990772916863,08045754427A358000,88,0.0,2015-04-28 07:33:53,1,4,1,12.0
78,990772897288,0804260FA283358000,88,0.0,2015-04-28 07:27:57,1,4,1,12.0
79,990264024389,08040C46DA98248000,52,0.0,2015-04-28 07:28:35,1,4,1,12.0
83,990195653641,0804204021741B8000,52,0.0,2015-04-28 07:31:11,1,4,1,12.0
84,990774870328,080E46166207481000,52,0.0,2015-04-28 06:36:09,1,4,1,12.0
85,970074486150,08A24F7ECF5C200800,52,0.0,2015-04-28 06:48:58,1,4,1,12.0
86,970074762659,08126E8DCF3E200800,52,0.0,2015-04-28 06:49:04,1,4,1,12.0
88,996264019907,08045F3702D6238000,53,0.0,2015-04-28 06:51:10,1,4,1,12.0
92,990164443289,080441326294248000,52,0.0,2015-04-28 07:09:17,1,4,1,12.0
...,...,...,...,...,...,...,...,...,...
2309456,990770780195,0804482B3A3F2F8000,52,190.0,2015-04-30 18:41:26,2,1,9,1.0
2309457,970472651789,080E22B1B00B091E00,52,190.0,2015-04-30 18:41:30,2,1,9,1.0
2309458,990500123477,0804234162B82B8000,52,190.0,2015-04-30 18:41:57,2,1,9,1.0
2309459,976674251057,088D3212941518A000,53,190.0,2015-04-30 18:41:59,2,1,9,1.0
2309461,996195701807,08041B4A41921B8000,53,475.0,2015-04-30 18:42:05,2,1,9,1.0
2309462,997169095158,08043942E2F7328000,80,190.0,2015-04-30 18:42:08,2,1,9,1.0
2309465,976072935213,088F79DF042D200800,53,285.0,2015-04-30 18:42:39,2,1,9,1.0
2309466,990572714724,08044B130A7A358000,52,285.0,2015-04-30 18:42:42,2,1,9,1.0
2309467,996164189939,08045C273A98268000,53,380.0,2015-04-30 18:43:12,2,1,9,1.0
2309468,996162760916,08042833BA95208000,53,285.0,2015-04-30 18:43:18,2,1,9,1.0
2309469,997165599953,0804141D8AFE228000,80,190.0,2015-04-30 18:43:21,2,1,9,1.0
2309471,996161291983,08041D4A31AE238000,53,190.0,2015-04-30 18:44:06,2,1,9,1.0
2309472,996096236072,0804093911921B8000,53,190.0,2015-04-30 18:44:09,2,1,9,1.0
2309476,976674236590,088D3212940717D200,53,190.0,2015-04-30 18:44:35,2,1,9,1.0
2309477,996160611765,08045B3921001F8000,53,190.0,2015-04-30 18:44:38,2,1,9,1.0
2309480,996096185108,0804385F91901B8000,53,150.0,2015-04-30 18:44:53,2,1,9,1.0
2309483,996572106151,08043538128C338000,53,285.0,2015-04-30 18:45:19,2,1,9,1.0
2309484,970672792588,080D3710580AA9BA00,52,190.0,2015-04-30 18:45:22,2,1,9,1.0
2309485,990163538317,08045341921F1D8000,52,190.0,2015-04-30 18:46:05,2,1,9,1.0
2309486,990772915708,0804420CA283358000,88,190.0,2015-04-30 19:29:31,2,1,14,11.0
2309488,970472621063,080E2285AB150E2500,52,285.0,2015-04-30 19:30:36,2,1,14,11.0
2309490,970672776748,080D2914671783B100,52,190.0,2015-04-30 19:30:45,2,1,14,11.0
2309491,990572716006,080436126A84368000,52,380.0,2015-04-30 19:30:48,2,1,14,11.0
2309492,990571157745,08041B4EDA39318000,52,340.0,2015-04-30 19:30:54,2,1,14,11.0
2309493,996060349674,0804511029841D8000,53,190.0,2015-04-30 19:30:59,2,1,14,11.0
2309494,990172172398,08045A404AA3328000,52,150.0,2015-04-30 19:31:02,2,1,14,11.0
2309495,990773066764,080D3710471987D400,52,190.0,2015-04-30 19:31:08,2,1,14,11.0
2309496,970674210990,080D371066059FD400,52,475.0,2015-04-30 19:31:20,2,1,14,11.0
2309497,996172342465,080448176A8C338000,53,475.0,2015-04-30 19:31:36,2,1,14,11.0
2309498,997168296933,08045E406A612B8000,80,190.0,2015-04-30 19:31:50,2,1,14,11.0

In [15]:
# Number of unique user IDs in all_after, new line only
orig_no_unique=len(all_after.where(all_after['Line_Id']==3).dropna(how="any").Card_Id.unique())
orig_no_unique

341359

In [17]:
all_after_newline=all_unique.where(all_unique['Line_Id']==3).dropna(how="any")

In [18]:
# New line and ids in AFTER only 
all_after_newline

,Card_Id,Card_Id_Long,Card_Type,Fare,Time,Entry_Or_Exit,Line_Id,StationId,Device_Id
186163,9.902638e+11,08041A49322A238000,52.0,0.0,2015-04-28 09:34:26,1.0,3.0,41.0,3.0
186164,9.902638e+11,0804543B5AED228000,52.0,0.0,2015-04-28 09:34:28,1.0,3.0,41.0,3.0
186165,9.940000e+11,0804092E12B1238000,52.0,0.0,2015-04-28 09:35:31,1.0,3.0,41.0,3.0
186166,9.907721e+11,08045513524B2B8000,52.0,0.0,2015-04-28 09:35:43,1.0,3.0,41.0,3.0
186168,9.971626e+11,0804552752CA218000,85.0,0.0,2015-04-28 09:35:58,1.0,3.0,41.0,3.0
186169,9.902616e+11,08042F3CD9771B8000,52.0,0.0,2015-04-28 09:36:03,1.0,3.0,41.0,3.0
186172,9.961607e+11,0804521D296E1C8000,53.0,0.0,2015-04-28 09:36:17,1.0,3.0,41.0,3.0
186173,9.901722e+11,08040A2692A1328000,52.0,0.0,2015-04-28 09:36:20,1.0,3.0,41.0,3.0
186174,9.962954e+11,0804113D41261D8000,53.0,0.0,2015-04-28 09:36:27,1.0,3.0,41.0,3.0
186175,9.971653e+11,08042D0E6A3E228000,80.0,0.0,2015-04-28 09:36:42,1.0,3.0,41.0,3.0
186176,9.961628e+11,08045958B295208000,53.0,0.0,2015-04-28 09:42:03,1.0,3.0,41.0,3.0
186179,9.760729e+11,080FA9DE047C200800,53.0,0.0,2015-04-28 09:42:19,1.0,3.0,41.0,3.0
186181,9.704713e+11,080E20277902171B00,52.0,0.0,2015-04-28 09:43:10,1.0,3.0,41.0,3.0
186182,9.960969e+11,08045153D1701B8000,53.0,0.0,2015-04-28 09:43:20,1.0,3.0,41.0,3.0
186184,9.760701e+11,082F441D96E0200800,53.0,0.0,2015-04-28 08:30:25,1.0,3.0,41.0,3.0
186188,9.905727e+11,0804530D7284368000,52.0,0.0,2015-04-28 08:30:49,1.0,3.0,41.0,3.0
186190,9.700745e+11,086F706483F8200800,52.0,0.0,2015-04-28 08:31:00,1.0,3.0,41.0,3.0
186195,9.901638e+11,08044E2D7AB0238000,52.0,0.0,2015-04-28 08:31:16,1.0,3.0,41.0,3.0
186197,9.907721e+11,08040A3C4A4B2B8000,52.0,0.0,2015-04-28 08:31:25,1.0,3.0,41.0,3.0
186198,9.907745e+11,080E46166207164300,52.0,0.0,2015-04-28 08:31:28,1.0,3.0,41.0,3.0
186203,9.907745e+11,08042C57D24F3C8000,52.0,0.0,2015-04-28 08:31:49,1.0,3.0,41.0,3.0
186207,9.961613e+11,08044012C1971B8000,53.0,0.0,2015-04-28 10:03:16,1.0,3.0,41.0,3.0
186208,9.759721e+11,081D12060001000000,52.0,0.0,2015-04-28 10:03:18,1.0,3.0,41.0,3.0
186209,9.764750e+11,080E2494F9110B1700,53.0,0.0,2015-04-28 10:03:23,1.0,3.0,41.0,3.0
186211,9.706742e+11,080D371066090CC500,52.0,0.0,2015-04-28 10:05:08,1.0,3.0,41.0,3.0
186213,9.764713e+11,080E20B829092C0D00,53.0,0.0,2015-04-28 10:06:21,1.0,3.0,41.0,3.0
186214,9.971682e+11,0804324BD22F2C8000,80.0,0.0,2015-04-28 10:06:58,1.0,3.0,41.0,3.0
186215,9.905001e+11,08046B3942BA2B8000,52.0,0.0,2015-04-28 10:08:05,1.0,3.0,41.0,3.0
186216,9.700745e+11,0802B17CCF00200800,52.0,0.0,2015-04-28 10:08:25,1.0,3.0,41.0,3.0
186219,9.962615e+11,0804522E59B71B8000,53.0,0.0,2015-04-28 10:10:19,1.0,3.0,41.0,3.0
...,...,...,...,...,...,...,...,...,...
2273008,9.961636e+11,0804251DB226238000,53.0,380.0,2015-04-30 14:03:17,2.0,3.0,50.0,20.0
2273011,9.901642e+11,0804312D3203208000,52.0,570.0,2015-04-30 09:12:53,2.0,3.0,50.0,20.0
2273013,9.903635e+11,080411319A1D1D8000,52.0,435.0,2015-04-30 09:13:06,2.0,3.0,50.0,20.0
2273015,9.971670e+11,0804341502C8238000,55.0,0.0,2015-04-30 09:13:24,2.0,3.0,50.0,20.0
2273018,9.764713e+11,080E2027180C2F3E00,53.0,245.0,2015-04-30 09:16:15,2.0,3.0,50.0,20.0
2273019,9.961640e+11,08045C481203218000,53.0,150.0,2015-04-30 09:20:27,2.0,3.0,50.0,20.0
2273020,9.965722e+11,08046A3F2274348000,53.0,380.0,2015-04-30 14:48:37,2.0,3.0,50.0,20.0
2273023,9.971668e+11,08045A150234268000,85.0,200.0,2015-04-30 15:24:16,2.0,3.0,50.0,20.0
2273024,9.764713e+11,080E20277907261100,53.0,190.0,2015-04-30 15:24:19,2.0,3.0,50.0,20.0
2273026,9.965722e+11,080425512A74348000,53.0,340.0,2015-04-30 15:24:27,2.0,3.0,50.0,20.0
2273028,9.901712e+11,08043E4F52462C8000,52.0,340.0,2015-04-30 15:24:35,2.0,3.0,50.0,20.0
2273029,9.760715e+11,080FD888055A200800,54.0,100.0,2015-04-30 15:26:08,2.0,3.0,50.0,20.0
2273031,9.700713e+11,082F35AD04B3200800,52.0,380.0,2015-04-30 14:57:26,2.0,3.0,50.0,20.0
2273036,9.965001e+11,0804151A12B92B8000,53.0,380.0,2015-04-30 15:29:43,2.0,3.0,50.0,20.0
2273037,9.764750e+11,080E2494F90E161C00,54.0,100.0,2015-04-30 15:30:55,2.0,3.0,50.0,20.0
2273039,9.965001e+11,0804524C62B82B8000,53.0,340.0,2015-04-30 15:33:24,2.0,3.0,50.0,20.0
2273041,9.700748e+11,084FBB708307200800,52.0,190.0,2015-04-30 10:45:55,2.0,3.0,50.0,20.0
2273042,9.901639e+11,080458225A03218000,52.0,340.0,2015-04-30 10:46:17,2.0,3.0,50.0,20.0
2273043,9.971677e+11,08040D2A3205208000,55.0,0.0,2015-04-30 10:46:42,2.0,3.0,50.0,20.0
2273044,9.901638e+11,08042B598A79248000,52.0,245.0,2015-04-30 10:33:33,2.0,3.0,50.0,20.0
2273045,9.971660e+11,0804374782C6238000,80.0,380.0,2015-04-30 10:33:58,2.0,3.0,50.0,20.0
2273046,9.961723e+11,0804083ED271348000,53.0,245.0,2015-04-30 10:39:51,2.0,3.0,50.0,20.0
2273047,9.965000e+11,08042E2322E8268000,53.0,190.0,2015-04-30 10:40:00,2.0,3.0,50.0,20.0
2273050,9.961640e+11,08041027AAB9238000,53.0,475.0,2015-04-30 11:32:13,2.0,3.0,50.0,20.0
2273054,9.971667e+11,0804262892B9238000,55.0,0.0,2015-04-30 11:32:46,2.0,3.0,50.0,20.0
2273055,9.761700e+11,088B1112340B1A1600,53.0,150.0,2015-04-30 11:39:39,2.0,3.0,50.0,20.0
2273056,9.971669e+11,0804453272C9208000,85.0,250.0,2015-04-30 11:39:49,2.0,3.0,50.0,20.0
2273057,9.965721e+11,08043A451A8C338000,54.0,250.0,2015-04-30 11:39:54,2.0,3.0,50.0,20.0
2273058,9.981615e+11,0804574C89031F8000,53.0,190.0,2015-04-30 11:40:02,2.0,3.0,50.0,20.0
2273059,9.971663e+11,0804184482C6238000,80.0,435.0,2015-04-30 10:39:54,2.0,3.0,50.0,20.0

In [19]:
no_newriders=len(all_after_newline.Card_Id.unique())
no_newriders

221533

In [20]:
orig_no_unique

341359

In [21]:
# Induced demand in terms of no of individuals
from __future__ import division
induced_dem=no_newriders/orig_no_unique*100
induced_dem

64.89736611602449

In [22]:
# Induced demand in terms of no of trips
len(all_after_newline)/len(all_after.where(all_after['Line_Id']==3).dropna(how="any"))*100

53.20250574605119